name: Release Package

on:
  release:
    types: [published]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
  
      - name: Extract build version
        id: get_version
        uses: battila7/get-version-action@v2

      - name: Build package
        uses: addnab/docker-run-action@v3
        with:
          image: aclemons/slackware:15.0
          options: -v ${{ github.workspace }}:/workspace -e VERSION=${{ steps.get_version.outputs.version-without-v }}
          run: |
            cd /workspace
            ./scripts/build_package.sh

      - name: Wait a bit
        run: sleep 5

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: archive/ACME-${{ steps.get_version.outputs.version-without-v }}-noarch-1.txz

      - name: Check out main
        uses: actions/checkout@v4
        with:
          ref: main
          path: 'main-repo'
      
      - name: Add binary to archive folder
        run: |
          cd main-repo
          mkdir -p archive
          cp ../archive/ACME-${{ steps.get_version.outputs.version-without-v }}-noarch-1.txz archive/
          git branch
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git add archive/ACME-${{ steps.get_version.outputs.version-without-v }}-noarch-1.txz
          git commit -m "Added binary for version ${{ steps.get_version.outputs.version-without-v }}"
          git push
      
      - name: MD5
        run: |
          echo "MD5; `md5sum -b archive/ACME-${{ steps.get_version.outputs.version-without-v }}-noarch-1.txz  | awk '{print $1}'`"
